apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-will-ingress
  labels:
    app: app-will-svc
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-will-svc
            port:
              number: 8080
