apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-will-ingress
  labels:
    app: app-will-svc
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app-will-svc
          servicePort: 8080
